"""empty message

Revision ID: 4df80323c479
Revises: f0b32a10479c
Create Date: 2020-01-13 10:35:19.753019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df80323c479'
down_revision = 'f0b32a10479c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('closet_id', sa.Integer(), nullable=True))
    op.add_column('clothing_items', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('clothing_items', sa.Column('name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'clothing_items', 'closets', ['closet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clothing_items', type_='foreignkey')
    op.drop_column('clothing_items', 'name')
    op.drop_column('clothing_items', 'image_url')
    op.drop_column('clothing_items', 'closet_id')
    # ### end Alembic commands ###
